export const projects = [
  {
    title: "ADITYA GURU",
    image: "/img1.jpeg",
    year: 2024,
    regNo: "22541001",
    department: "CSE",
    type: "RESEARCH",
    duration: "6 MONTHS",
    stipend: "250000",
    bio: "Published at ACL'24 on human-computer interaction and adaptive interfaces. His work explores how AI can improve accessibility in digital platforms, combining deep learning with user-centered design principles to create more inclusive technology.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["ACL'24", "HCI", "AI"]
  },
  {
    title: "SIDHARTH SUKLA",
    image: "/img2.jpeg",
    year: 2023,
    regNo: "22531002",
    department: "CAI",
    type: "RESEARCH",
    duration: "4 MONTHS",
    stipend: "200000",
    bio: "Presented at ICML'24 on novel machine learning algorithms for edge computing. Developed efficient model compression techniques that reduce inference time by 40% while maintaining accuracy, making AI deployment feasible on resource-constrained devices.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["ICML'24", "ML", "ALGORITHMS"]
  },
  {
    title: "MANAS KUMAR",
    image: "/img3.jpeg",
    year: 2024,
    regNo: "22541003",
    department: "CSE",
    type: "INTERNSHIP",
    duration: "3 MONTHS",
    stipend: "350000",
    bio: "Completed a design internship at Google, working on UX improvements for Google Workspace. Redesigned the collaboration flow in Google Docs, resulting in a 25% increase in user engagement during real-time editing sessions.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["GOOGLE", "DESIGN", "UX"]
  },
  {
    title: "RAJNEESH KUMAR",
    image: "/img4.jpeg",
    year: 2023,
    regNo: "22531004",
    department: "CII",
    type: "RESEARCH",
    duration: "8 MONTHS",
    stipend: "300000",
    bio: "Published at ACM CHI'25 on brain-computer interfaces and cognitive psychology. Designed a non-invasive BCI system that allows users to control digital interfaces through thought, opening new possibilities for assistive technology.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["ACMCHI'25", "BCI", "PSYCHOLOGY"]
  },
  {
    title: "AYUSH GUPTA",
    image: "/img5.jpeg",
    year: 2024,
    regNo: "22541005",
    department: "CSE",
    type: "INTERNSHIP",
    duration: "6 MONTHS",
    stipend: "400000",
    bio: "Remote internship at Meta working on AI infrastructure. Built scalable data pipelines that process over 10 million requests daily, significantly improving the reliability of Meta's machine learning training systems.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["META", "REMOTE", "AI"]
  },
  {
    title: "KRISHANU",
    image: "/img6.jpeg",
    year: 2022,
    regNo: "22521006",
    department: "CCE",
    type: "RESEARCH",
    duration: "5 MONTHS",
    stipend: "150000",
    bio: "Published at NeurIPS'23 on adversarial machine learning and cybersecurity. Developed novel defense mechanisms against gradient-based attacks, improving model robustness by 35% in real-world deployment scenarios.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["NEURIPS'23", "ML", "CYBERSECURITY"]
  },
  {
    title: "NEHA MISHRA",
    image: "/img7.jpeg",
    year: 2024,
    regNo: "22541007",
    department: "ECE",
    type: "INTERNSHIP",
    duration: "4 MONTHS",
    stipend: "320000",
    bio: "Design internship at Apple focusing on human-computer interaction for accessibility features. Contributed to VoiceOver improvements that made iOS more usable for visually impaired users across 30+ languages.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["APPLE", "DESIGN", "HCI"]
  },
  {
    title: "SHARDOOL",
    image: "/img8.jpeg",
    year: 2023,
    regNo: "22531008",
    department: "CAI",
    type: "RESEARCH",
    duration: "6 MONTHS",
    stipend: "280000",
    bio: "Published at ICLR'24 on efficient training algorithms for large language models. Proposed a novel optimization technique that reduces training time by 30% without compromising model quality.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["ICLR'24", "ALGORITHMS", "AI"]
  },
  {
    title: "DANUSH KHANNA",
    image: "/img9.jpeg",
    year: 2024,
    regNo: "22541009",
    department: "CSE",
    type: "INTERNSHIP",
    duration: "6 MONTHS",
    stipend: "380000",
    bio: "Research internship at Microsoft in the Media and Data Science Research Lab. Worked on generative AI for content creation, developing models that assist designers in creating adaptive user interfaces for enterprise applications.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["MICROSOFT", "HCI", "DESIGN"]
  },
  {
    title: "BITHAL MOHANTY",
    image: "/img10.jpeg",
    year: 2023,
    regNo: "22531010",
    department: "MEE",
    type: "RESEARCH",
    duration: "7 MONTHS",
    stipend: "220000",
    bio: "Published at CHI'24 on brain-computer interfaces for cognitive assessment. Developed a portable EEG-based system that can detect early signs of cognitive decline with 92% accuracy.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["CHI'24", "BCI", "PSYCHOLOGY"]
  },
  {
    title: "ADITYA SHARMA",
    image: "/img11.jpeg",
    year: 2022,
    regNo: "22521011",
    department: "ITE",
    type: "INTERNSHIP",
    duration: "5 MONTHS",
    stipend: "450000",
    bio: "Internship at Tesla on autonomous driving AI systems. Contributed to the perception stack by improving object detection in low-light conditions, achieving a 15% reduction in false negatives.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["TESLA", "AI", "CYBERSECURITY"]
  },
  {
    title: "JHANVI",
    image: "/img12.jpeg",
    year: 2024,
    regNo: "22541012",
    department: "CSE",
    type: "RESEARCH",
    duration: "6 MONTHS",
    stipend: "260000",
    bio: "Published at UIST'24 on human-computer interaction and machine learning for creative tools. Built an intelligent sketching assistant that helps designers prototype interfaces 40% faster using predictive layout generation.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["UIST'24", "HCI", "ML"]
  },
  {
    title: "ADAMYA",
    image: "/img13.jpeg",
    year: 2024,
    regNo: "22541013",
    department: "CII",
    type: "INTERNSHIP",
    duration: "3 MONTHS",
    stipend: "310000",
    bio: "Design internship at Adobe working on Creative Cloud UX improvements. Redesigned the layer management system in Photoshop, reducing workflow friction and receiving positive feedback from 85% of beta testers.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["ADOBE", "DESIGN", "UX"]
  },
  {
    title: "AVANT",
    image: "/img14.jpeg",
    year: 2023,
    regNo: "22531014",
    department: "CAI",
    type: "RESEARCH",
    duration: "5 MONTHS",
    stipend: "240000",
    bio: "Published at CVPR'24 on computer vision and efficient neural architectures. Developed a lightweight object detection model that runs in real-time on mobile devices with only 2MB of memory footprint.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["CVPR'24", "AI", "ALGORITHMS"]
  },
  {
    title: "AVINA",
    image: "/img15.jpeg",
    year: 2023,
    regNo: "22531015",
    department: "CCE",
    type: "INTERNSHIP",
    duration: "6 MONTHS",
    stipend: "370000",
    bio: "Remote internship at Netflix working on recommendation systems. Improved the content recommendation algorithm using multi-modal learning, increasing viewer engagement by 12% on the platform.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["NETFLIX", "REMOTE", "ML"]
  },
  {
    title: "ANITA SINGH",
    image: "/img16.jpeg",
    year: 2024,
    regNo: "22541016",
    department: "ECE",
    type: "INTERNSHIP",
    duration: "4 MONTHS",
    stipend: "290000",
    bio: "UX internship at Spotify redesigning the podcast discovery experience. Conducted user research with 200+ participants and designed a new browsing interface that increased podcast listening time by 18%.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["SPOTIFY", "UX", "DESIGN"]
  },
  {
    title: "PETALLOOP",
    image: "/img17.jpeg",
    year: 2023,
    regNo: "22531017",
    department: "MEE",
    type: "RESEARCH",
    duration: "7 MONTHS",
    stipend: "210000",
    bio: "Published at ICCV'24 on computer vision for security applications. Developed a real-time anomaly detection system for surveillance footage that reduces false alarms by 60% compared to existing solutions.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["ICCV'24", "AI", "CYBERSECURITY"]
  },
  {
    title: "ARJUN PATEL",
    image: "/img18.jpeg",
    year: 2024,
    regNo: "22541018",
    department: "ITE",
    type: "INTERNSHIP",
    duration: "6 MONTHS",
    stipend: "420000",
    bio: "Machine learning internship at Amazon working on supply chain optimization. Built predictive models that reduced delivery time variance by 22%, directly improving customer satisfaction scores.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["AMAZON", "ML", "ALGORITHMS"]
  },
  {
    title: "PRIYA SINGH",
    image: "/img19.jpeg",
    year: 2023,
    regNo: "22531019",
    department: "CSE",
    type: "RESEARCH",
    duration: "8 MONTHS",
    stipend: "270000",
    bio: "Published at SIGCHI'25 on human-computer interaction and cognitive psychology. Investigated how interface animations affect user attention span and designed guidelines that improve task completion rates by 28%.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["SIGCHI'25", "HCI", "PSYCHOLOGY"]
  },
  {
    title: "ROHIT SHARMA",
    image: "/img20.jpeg",
    year: 2024,
    regNo: "22541020",
    department: "CSE",
    type: "INTERNSHIP",
    duration: "5 MONTHS",
    stipend: "390000",
    bio: "AI internship at NVIDIA working on GPU-accelerated deep learning. Optimized training pipelines for large vision models, achieving 2.5x speedup on the latest H100 hardware through custom CUDA kernels.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["NVIDIA", "AI", "ML"]
  },
  {
    title: "KAVYA REDDY",
    image: "/img21.jpeg",
    year: 2022,
    regNo: "22521021",
    department: "CAI",
    type: "RESEARCH",
    duration: "6 MONTHS",
    stipend: "180000",
    bio: "Published at AAAI'24 on brain-computer interfaces and efficient algorithms. Designed a signal processing pipeline that decodes motor imagery EEG signals with 85% accuracy using only 8 electrodes.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["AAAI'24", "BCI", "ALGORITHMS"]
  },
  {
    title: "VIKASH KUMAR",
    image: "/img22.jpeg",
    year: 2023,
    regNo: "22531022",
    department: "CII",
    type: "INTERNSHIP",
    duration: "4 MONTHS",
    stipend: "340000",
    bio: "Remote internship at Uber building human-computer interaction tools for driver safety. Developed a real-time fatigue detection system using computer vision that reduced accident rates by 30% in pilot testing.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["UBER", "REMOTE", "HCI"]
  },
  {
    title: "SNEHA GUPTA",
    image: "/img23.jpeg",
    year: 2024,
    regNo: "22541023",
    department: "CCE",
    type: "RESEARCH",
    duration: "5 MONTHS",
    stipend: "230000",
    bio: "Published at ECCV'24 on generative AI for design automation. Created a text-to-layout system that generates professional UI mockups from natural language descriptions, reducing early-stage design time by 60%.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["ECCV'24", "AI", "DESIGN"]
  },
  {
    title: "ANKIT VERMA",
    image: "/img24.jpeg",
    year: 2022,
    regNo: "22521024",
    department: "ITE",
    type: "INTERNSHIP",
    duration: "6 MONTHS",
    stipend: "480000",
    bio: "Internship at OpenAI contributing to language model safety research. Developed evaluation frameworks for detecting harmful outputs, improving the safety filter accuracy by 40% in GPT-4 deployments.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["OPENAI", "ML", "CYBERSECURITY"]
  },
  {
    title: "RAVI SHARMA",
    image: "/img25.jpeg",
    year: 2024,
    regNo: "22541025",
    department: "MEE",
    type: "RESEARCH",
    duration: "7 MONTHS",
    stipend: "200000",
    bio: "Published at WACV'25 on psychology-informed AI systems. Built emotion-aware interfaces that adapt to user mood states, demonstrating a 35% improvement in user satisfaction during extended interaction sessions.",
    socials: { linkedin: "#", website: "#" },
    href: "/sample-project",
    tags: ["WACV'25", "PSYCHOLOGY", "AI"]
  },
];
